#!/bin/bash

# finds the nuber of emails stored locally in my inbox with offline imap email account

if ! new_mails=$(du -a ~/.local/share/mail/tobias/INBOX/new/* 2>/dev/null | wc -l); then
		new_mails=0
fi

if [ "$new_mails" -gt 0 ]; then
		echo "$new_mails"
else
		echo ""
fi
