#!/bin/bash

# the script assumes that the user is always looking for HDMI3 as the only option
my_laptop_external_monitor=$(xrandr --query | grep 'HDMI3')

if [[ $my_laptop_external_monitor = *connected* ]]; then
  xrandr --output eDP1 --primary --mode 2880x1800 --rotate normal --output HDMI3 --mode 1920x1080 --rotate normal --right-of eDP1
fi