#!/bin/bash

# the purpose of this script is to output a searchable menu of vim keybindings
# it takes a plain text file using this simple shitty syntax:
# a line containing the title of a general section is preceded with the with "section "
# a line containing an entry is preceded with "entry "
# change the location of your cheatsheet
# yep, it's simple and shitty but it will give a highly usable and searchable cheatsheet

: '

declare -A keys

eval "$(cat ~/documents/cheatsheets/vim_cheatsheet | awk '
  BEGIN {foundkeys=0}
  {
    if($1=="mode") {ismode=1}
    if($1=="}")    {ismode=0}
    gsub(/["]/,"\\\"",$0)
    original=$0
    for(k in variables){
      gsub("[$]"k,variables[k],$0)
    }
    if(ismode!=1){
      gsub("[$]","\\$",original)
      if($0!~"exec"){msg="i3-msg "}
      else {msg=""}
      gsub(/bindsym|--release|exec|--no-startup-id/,"",$0)
      
      gsub("+","",$1)
      sub("Mod4","#",$1)
      sub("Mod1","!",$1)
      sub("Control","^",$1)
      sub("Shift","+",$1)
      bindsym=$1
      $1=""
      sub(/^[[:space:]]*/,"",$0)
      cmd=$0
      realcmd=msg cmd
      print "keys[" foundkeys "-bindsym]=\"" bindsym "\""
      print "keys[" foundkeys "-cmd]=\"" cmd "\""
      print "keys[" foundkeys "-realcmd]=\"" realcmd "\""
      print "keys[" foundkeys "-original]=\"" original "\""
      foundkeys++
    }
    if($1=="set"){
      sub("[$]","",$2)
      uservar=$2
      $1=$2=""
      sub(/^[[:space:]]*/,"",$0)
      userval=$0
      variables[uservar]=userval
    }
    
  }
  END {print "foundkeys=" foundkeys}
')"

selected="$({
  for ((i=0;i<foundkeys;i++)); do
    echo "${keys[${i}-bindsym]}" "${keys[${i}-cmd]}"
  done
} | rofi -dmenu -format i)"

[[ -z $selected ]] && exit 1

eval "${keys[${selected}-realcmd]}"

'